### PR TITLE
some more lineageos bringup and FM from tissot Mi A1

### PR DESCRIPTION
**Pull request by adil5233**

### CODE REVIEW

**Comment by ironmerc** [comment]
Tissot Blobs feks wifi

**Comment by ironmerc** [comment]
Have u tired using tissot wcnss_service ?

**Review by ironmerc — APPROVED** [review]

**Comment by andreysanyuk** [comment]
@DeckardShaw 
Did you test this one?  land: Kang tissot wcnss_service

**Comment by RiteshSaxena** [comment]
these changes are fine....

**Pull request merged**
